name: CI/CD DevOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Welcome Message
        run: echo "Hello Abbas! GitHub Actions is working."
